services:
  - type: web
    name: kaamwalibai-backend
    env: node
    region: oregon
    buildCommand: npm install
    preDeployCommand: npm run migrate-and-seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    rootDir: backend
    healthCheckPath: /
